version: "3.8"

services:
  # infra
  consul:
    image: consul
    container_name: consul
    restart: always
    ports:
      - 8500:8500
    networks:
      - distributed-estore
    volumes:
      - consul:/consul/data

  # infra
  fabio:
    image: fabiolb/fabio
    container_name: fabio
    restart: always
    environment:
    - FABIO_REGISTRY_CONSUL_ADDR=consul:8500
    networks:
      - distributed-estore
    ports:
    - 9998:9998
    - 9999:9999

  # infra
  rabbitmq:
    image: rabbitmq:3-management
    hostname: my-rabbit
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - distributed-estore
    volumes: 
      - rabbitmq:/var/lib/rabbitmq

# microservice
  api-gateway:
    image: distributed.estore.api.gateway
    restart: always
    ports:
      - 5000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RABBIT_HOSTNAME=rabbitmq
    depends_on:
      - "consul"
      - "fabio"
      - "rabbitmq"
    networks:
      - distributed-estore

  # microservice
  product-service:
    image: distributed.estore.services.product
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RABBIT_HOSTNAME=rabbitmq
    ports:
      - '5001:80'
    depends_on:
      - "consul"
      - "fabio"
      - "rabbitmq"
    networks:
     - distributed-estore

networks:
  distributed-estore:
    name: distributed-estore-network
    external: true

volumes:
  consul:
    driver: local
  rabbitmq:
    driver: local