version: "3.8"

services:      
  api-gateway:
    image: distributed.estore.api.gateway
    restart: always
    ports:
      - '80:80'
    # depends_on:
    #  - "consul"
    #  - "fabio"
    # - "rabbitmq"
    networks:
      - distributed-estore

  # microservice
  # product-service:
  #  image: distributed.estore.services.product
  #  restart: always
  #  ports:
  #    - '5001:80'
  #  depends_on:
  #    - "consul"
  #    - "fabio"
  #    - "rabbitmq"
  #  networks:
  #   - distributed-estore

networks:
  distributed-estore:
    name: distributed-estore-network
    external: true