version: "3.8"

services:
    consul:
      image: consul
      container_name: consul
      restart: always
      ports:
        - 8500:8500
      networks:
        - distributed-estore
      volumes:
        - consul:/consul/data

    fabio:
      image: fabiolb/fabio
      container_name: fabio
      restart: always
      environment:
      - FABIO_REGISTRY_CONSUL_ADDR=consul:8500
      networks:
        - distributed-estore
      ports:
      - 9998:9998
      - 9999:9999

    rabbitmq:
      image: rabbitmq:3-management
      hostname: my-rabbit
      container_name: rabbitmq
      restart: always
      ports:
        - 5672:5672
        - 15672:15672
      networks:
        - distributed-estore
      volumes: 
        - rabbitmq:/var/lib/rabbitmq

    mongo:
      image: mongo
      container_name: mongo
      restart: always
      ports:
        - 27017:27017
      networks:
        - distributed-estore
      # network_mode: host
      volumes:
        - mongo:/data/db

    api-gateway:
      image: distributed.estore.api.gateway
      restart: always
      ports:
        - 5000:80
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=http://+:80
        - RABBIT_HOSTNAME=rabbitmq
      networks:
        - distributed-estore
      depends_on:
        - "consul"
        - "fabio"
        - "rabbitmq"
        - "mongo"

    product-service:
      image: distributed.estore.services.product
      restart: always
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=http://+:80
        - RABBIT_HOSTNAME=rabbitmq
      ports:
        - '5001:80'
      networks:
       - distributed-estore
      depends_on:
        - "consul"
        - "fabio"
        - "rabbitmq"
        - "mongo"

    identity-service:
      image: distributed.estore.services.identity
      restart: always
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=http://+:80
      ports:
        - '5002:80'
      networks:
      - distributed-estore
      depends_on:
        - "consul"
        - "fabio"
        - "rabbitmq"
        - "mongo"
      
    order-service:
      image: distributed.estore.services.order
      restart: always
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=http://+:80
        - RABBIT_HOSTNAME=rabbitmq
      ports:
        - '5005:80'
      networks:
      - distributed-estore
      depends_on:
        - "consul"
        - "fabio"
        - "rabbitmq"
        - "mongo"
      
    ui:
      image: distributed.estore.ui
      restart: always
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=http://+:80
      ports:
        - '44310:80'
      networks:
      - distributed-estore
      depends_on:
        - "consul"
        - "fabio"
        - "rabbitmq"
        - "mongo"

networks:
  distributed-estore:
    name: distributed-estore-network
    external: true

volumes:
  consul:
    driver: local
  rabbitmq:
    driver: local
  mongo:
    driver: local